# Dockerfile.mcp_db
FROM python:3.11-slim

WORKDIR /app

COPY requirements_mcp_db.txt ./
RUN pip install --no-cache-dir -r requirements_mcp_db.txt

COPY ./mcp_server.py ./mcp_server.py  

EXPOSE 8001
CMD ["python", "-u", "mcp_server.py"]